import type { Card } from './types';

/**
 * Official Splendor (Space Cowboys, 2014) 90-card development deck: 40/30/20
 * across levels 1/2/3. Transcribed from and cross-verified against two
 * independent open-source implementations (github.com/boardgamers/splendor,
 * which itself cross-checked github.com/bouk/splendimax and
 * github.com/seal256/splendor — all three agree).
 */
export const ALL_CARDS: Card[] = [
  { id: 'L1-01', level: 1, bonus: 'onyx', points: 0, cost: { diamond: 1, sapphire: 1, emerald: 1, ruby: 1 } },
  { id: 'L1-02', level: 1, bonus: 'onyx', points: 0, cost: { diamond: 1, sapphire: 1, emerald: 1, ruby: 2 } },
  { id: 'L1-03', level: 1, bonus: 'onyx', points: 0, cost: { diamond: 2, emerald: 1, ruby: 2 } },
  { id: 'L1-04', level: 1, bonus: 'onyx', points: 0, cost: { sapphire: 1, ruby: 3, onyx: 1 } },
  { id: 'L1-05', level: 1, bonus: 'onyx', points: 0, cost: { emerald: 2, ruby: 1 } },
  { id: 'L1-06', level: 1, bonus: 'onyx', points: 0, cost: { diamond: 2, emerald: 2 } },
  { id: 'L1-07', level: 1, bonus: 'onyx', points: 0, cost: { emerald: 3 } },
  { id: 'L1-08', level: 1, bonus: 'onyx', points: 1, cost: { sapphire: 4 } },
  { id: 'L1-09', level: 1, bonus: 'sapphire', points: 0, cost: { diamond: 1, emerald: 1, ruby: 1, onyx: 1 } },
  { id: 'L1-10', level: 1, bonus: 'sapphire', points: 0, cost: { diamond: 1, emerald: 1, ruby: 2, onyx: 1 } },
  { id: 'L1-11', level: 1, bonus: 'sapphire', points: 0, cost: { diamond: 1, emerald: 2, ruby: 2 } },
  { id: 'L1-12', level: 1, bonus: 'sapphire', points: 0, cost: { sapphire: 1, emerald: 3, ruby: 1 } },
  { id: 'L1-13', level: 1, bonus: 'sapphire', points: 0, cost: { diamond: 1, sapphire: 2 } },
  { id: 'L1-14', level: 1, bonus: 'sapphire', points: 0, cost: { diamond: 2, emerald: 2 } },
  { id: 'L1-15', level: 1, bonus: 'sapphire', points: 0, cost: { sapphire: 3 } },
  { id: 'L1-16', level: 1, bonus: 'sapphire', points: 1, cost: { ruby: 4 } },
  { id: 'L1-17', level: 1, bonus: 'diamond', points: 0, cost: { sapphire: 1, emerald: 1, ruby: 1, onyx: 1 } },
  { id: 'L1-18', level: 1, bonus: 'diamond', points: 0, cost: { sapphire: 1, emerald: 2, ruby: 1, onyx: 1 } },
  { id: 'L1-19', level: 1, bonus: 'diamond', points: 0, cost: { sapphire: 2, emerald: 2, onyx: 1 } },
  { id: 'L1-20', level: 1, bonus: 'diamond', points: 0, cost: { diamond: 1, sapphire: 1, onyx: 3 } },
  { id: 'L1-21', level: 1, bonus: 'diamond', points: 0, cost: { sapphire: 1, ruby: 2 } },
  { id: 'L1-22', level: 1, bonus: 'diamond', points: 0, cost: { diamond: 2, sapphire: 2 } },
  { id: 'L1-23', level: 1, bonus: 'diamond', points: 0, cost: { emerald: 3 } },
  { id: 'L1-24', level: 1, bonus: 'diamond', points: 1, cost: { emerald: 4 } },
  { id: 'L1-25', level: 1, bonus: 'emerald', points: 0, cost: { diamond: 1, sapphire: 1, ruby: 1, onyx: 1 } },
  { id: 'L1-26', level: 1, bonus: 'emerald', points: 0, cost: { diamond: 1, sapphire: 1, ruby: 1, onyx: 2 } },
  { id: 'L1-27', level: 1, bonus: 'emerald', points: 0, cost: { diamond: 2, sapphire: 1, ruby: 2 } },
  { id: 'L1-28', level: 1, bonus: 'emerald', points: 0, cost: { diamond: 1, emerald: 3, ruby: 1 } },
  { id: 'L1-29', level: 1, bonus: 'emerald', points: 0, cost: { emerald: 1, onyx: 2 } },
  { id: 'L1-30', level: 1, bonus: 'emerald', points: 0, cost: { sapphire: 2, ruby: 2 } },
  { id: 'L1-31', level: 1, bonus: 'emerald', points: 0, cost: { ruby: 3 } },
  { id: 'L1-32', level: 1, bonus: 'emerald', points: 1, cost: { onyx: 4 } },
  { id: 'L1-33', level: 1, bonus: 'ruby', points: 0, cost: { diamond: 1, sapphire: 1, emerald: 1, onyx: 1 } },
  { id: 'L1-34', level: 1, bonus: 'ruby', points: 0, cost: { diamond: 2, sapphire: 1, emerald: 1, onyx: 1 } },
  { id: 'L1-35', level: 1, bonus: 'ruby', points: 0, cost: { diamond: 2, emerald: 1, onyx: 2 } },
  { id: 'L1-36', level: 1, bonus: 'ruby', points: 0, cost: { diamond: 1, sapphire: 3, onyx: 1 } },
  { id: 'L1-37', level: 1, bonus: 'ruby', points: 0, cost: { emerald: 2, ruby: 1 } },
  { id: 'L1-38', level: 1, bonus: 'ruby', points: 0, cost: { sapphire: 2, onyx: 2 } },
  { id: 'L1-39', level: 1, bonus: 'ruby', points: 0, cost: { onyx: 3 } },
  { id: 'L1-40', level: 1, bonus: 'ruby', points: 1, cost: { onyx: 4 } },
  { id: 'L2-01', level: 2, bonus: 'onyx', points: 1, cost: { diamond: 3, sapphire: 2, emerald: 2 } },
  { id: 'L2-02', level: 2, bonus: 'onyx', points: 1, cost: { diamond: 3, sapphire: 2, onyx: 2 } },
  { id: 'L2-03', level: 2, bonus: 'onyx', points: 2, cost: { sapphire: 1, emerald: 4, ruby: 2 } },
  { id: 'L2-04', level: 2, bonus: 'onyx', points: 2, cost: { emerald: 5, ruby: 3 } },
  { id: 'L2-05', level: 2, bonus: 'onyx', points: 2, cost: { diamond: 5 } },
  { id: 'L2-06', level: 2, bonus: 'onyx', points: 3, cost: { onyx: 6 } },
  { id: 'L2-07', level: 2, bonus: 'sapphire', points: 1, cost: { sapphire: 2, emerald: 2, ruby: 3 } },
  { id: 'L2-08', level: 2, bonus: 'sapphire', points: 1, cost: { sapphire: 3, emerald: 2, onyx: 3 } },
  { id: 'L2-09', level: 2, bonus: 'sapphire', points: 2, cost: { diamond: 5, emerald: 3 } },
  { id: 'L2-10', level: 2, bonus: 'sapphire', points: 2, cost: { diamond: 2, sapphire: 4, ruby: 1 } },
  { id: 'L2-11', level: 2, bonus: 'sapphire', points: 2, cost: { emerald: 5 } },
  { id: 'L2-12', level: 2, bonus: 'sapphire', points: 3, cost: { ruby: 6 } },
  { id: 'L2-13', level: 2, bonus: 'diamond', points: 1, cost: { emerald: 3, ruby: 2, onyx: 2 } },
  { id: 'L2-14', level: 2, bonus: 'diamond', points: 1, cost: { diamond: 2, ruby: 3, onyx: 3 } },
  { id: 'L2-15', level: 2, bonus: 'diamond', points: 2, cost: { emerald: 1, ruby: 4, onyx: 2 } },
  { id: 'L2-16', level: 2, bonus: 'diamond', points: 2, cost: { sapphire: 3, ruby: 5 } },
  { id: 'L2-17', level: 2, bonus: 'diamond', points: 2, cost: { onyx: 5 } },
  { id: 'L2-18', level: 2, bonus: 'diamond', points: 3, cost: { onyx: 6 } },
  { id: 'L2-19', level: 2, bonus: 'emerald', points: 1, cost: { diamond: 3, ruby: 3, onyx: 2 } },
  { id: 'L2-20', level: 2, bonus: 'emerald', points: 1, cost: { diamond: 2, sapphire: 3, onyx: 2 } },
  { id: 'L2-21', level: 2, bonus: 'emerald', points: 2, cost: { sapphire: 2, onyx: 4 } },
  { id: 'L2-22', level: 2, bonus: 'emerald', points: 2, cost: { emerald: 5, ruby: 3 } },
  { id: 'L2-23', level: 2, bonus: 'emerald', points: 2, cost: { sapphire: 5 } },
  { id: 'L2-24', level: 2, bonus: 'emerald', points: 3, cost: { emerald: 6 } },
  { id: 'L2-25', level: 2, bonus: 'ruby', points: 1, cost: { diamond: 2, ruby: 2, onyx: 3 } },
  { id: 'L2-26', level: 2, bonus: 'ruby', points: 1, cost: { diamond: 2, emerald: 3, onyx: 3 } },
  { id: 'L2-27', level: 2, bonus: 'ruby', points: 2, cost: { diamond: 1, ruby: 4, onyx: 2 } },
  { id: 'L2-28', level: 2, bonus: 'ruby', points: 2, cost: { ruby: 3, onyx: 5 } },
  { id: 'L2-29', level: 2, bonus: 'ruby', points: 2, cost: { onyx: 5 } },
  { id: 'L2-30', level: 2, bonus: 'ruby', points: 3, cost: { ruby: 6 } },
  { id: 'L3-01', level: 3, bonus: 'onyx', points: 3, cost: { diamond: 3, sapphire: 3, emerald: 5, ruby: 3 } },
  { id: 'L3-02', level: 3, bonus: 'onyx', points: 4, cost: { ruby: 7 } },
  { id: 'L3-03', level: 3, bonus: 'onyx', points: 4, cost: { diamond: 3, ruby: 6, onyx: 3 } },
  { id: 'L3-04', level: 3, bonus: 'onyx', points: 5, cost: { diamond: 3, ruby: 7 } },
  { id: 'L3-05', level: 3, bonus: 'sapphire', points: 3, cost: { diamond: 3, emerald: 3, ruby: 3, onyx: 5 } },
  { id: 'L3-06', level: 3, bonus: 'sapphire', points: 4, cost: { diamond: 7 } },
  { id: 'L3-07', level: 3, bonus: 'sapphire', points: 4, cost: { diamond: 6, sapphire: 3, onyx: 3 } },
  { id: 'L3-08', level: 3, bonus: 'sapphire', points: 5, cost: { diamond: 7, onyx: 3 } },
  { id: 'L3-09', level: 3, bonus: 'diamond', points: 3, cost: { sapphire: 3, emerald: 3, ruby: 3, onyx: 5 } },
  { id: 'L3-10', level: 3, bonus: 'diamond', points: 4, cost: { onyx: 7 } },
  { id: 'L3-11', level: 3, bonus: 'diamond', points: 4, cost: { diamond: 3, sapphire: 6, onyx: 3 } },
  { id: 'L3-12', level: 3, bonus: 'diamond', points: 5, cost: { sapphire: 7, onyx: 3 } },
  { id: 'L3-13', level: 3, bonus: 'emerald', points: 3, cost: { diamond: 5, sapphire: 3, ruby: 3, onyx: 3 } },
  { id: 'L3-14', level: 3, bonus: 'emerald', points: 4, cost: { sapphire: 7 } },
  { id: 'L3-15', level: 3, bonus: 'emerald', points: 4, cost: { diamond: 3, sapphire: 3, emerald: 6 } },
  { id: 'L3-16', level: 3, bonus: 'emerald', points: 5, cost: { emerald: 7, ruby: 3 } },
  { id: 'L3-17', level: 3, bonus: 'ruby', points: 3, cost: { diamond: 3, sapphire: 3, emerald: 3, onyx: 5 } },
  { id: 'L3-18', level: 3, bonus: 'ruby', points: 4, cost: { emerald: 7 } },
  { id: 'L3-19', level: 3, bonus: 'ruby', points: 4, cost: { diamond: 3, emerald: 3, ruby: 6 } },
  { id: 'L3-20', level: 3, bonus: 'ruby', points: 5, cost: { sapphire: 3, emerald: 7 } },
];
